apiVersion: v1
kind: Service
metadata:
  name: embedder
  namespace: qbc12-hw03-c-samin-kakaei
  labels:
    app: embedder
spec:
  type: NodePort
  selector:
    app: embedder
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30113
    protocol: TCP
